### PR TITLE
Update to 1.21

### PR DESCRIPTION
**Pull request by ShrikerChestTrees**
Add support for **1.21**.

You are the only one who decided to make support for 1.20.6.
**Thank you!**

### CODE REVIEW

**Comment by ErinMax** [comment]
Hey! thx for this, i will merge it right now!

**Comment by tajemniktv** [comment]
(and he never did) 😭

**Comment by ErinMax** [comment]
IM SO SORRY LOL

**Comment by ErinMax** [comment]
@tajemniktv @ShrikerChestTrees it's done and it should be in the releases page right now!

**Pull request merged**
